# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test Base
      run: |
        pytest test/test_format.py
        pytest test/test_parse.py
        pytest test/test_localizer.py
    - name: Test ca
      run: |
        pytest test/test_format_ca.py
        pytest test/test_parse_ca.py
    - name: Test cs
      run: |
        pytest test/test_format_cs.py
        pytest test/test_parse_cs.py
    - name: Test da
      run: |
        pytest test/test_format_da.py
        pytest test/test_parse_da.py
    - name: Test de
      run: |
        pytest test/test_format_de.py
        pytest test/test_parse_de.py
    - name: Test en
      run: |
        pytest test/test_format_en.py
        pytest test/test_parse_en.py
    - name: Test es
      run: |
        pytest test/test_format_es.py
        pytest test/test_parse_es.py
    - name: Test fa
      run: |
        pytest test/test_format_fa.py
        pytest test/test_parse_fa.py
    - name: Test fr
      run: |
        pytest test/test_format_fr.py
        pytest test/test_parse_fr.py
    - name: Test hu
      run: |
        pytest test/test_format_hu.py
    - name: Test it
      run: |
        pytest test/test_format_it.py
        pytest test/test_parse_it.py
    - name: Test nl
      run: |
        pytest test/test_format_nl.py
        pytest test/test_parse_nl.py
    - name: Test pl
      run: |
        pytest test/test_format_pl.py
        pytest test/test_parse_pl.py
    - name: Test pt
      run: |
        pytest test/test_format_pt.py
        pytest test/test_parse_pt.py
    - name: Test ru
      run: |
        pytest test/test_format_ru.py
        pytest test/test_parse_ru.py
    - name: Test sl
      run: |
        pytest test/test_format_sl.py
    - name: Test sv
      run: |
        pytest test/test_format_sv.py
        pytest test/test_parse_sv.py
